import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { CtaLink } from "@/components/CtaLink";

export default function Blog({ slug }: { slug?: string }) {
  const list = trpc.blog.publicList.useQuery(undefined, { enabled: !slug });
  const detail = trpc.blog.publicBySlug.useQuery({ slug: slug ?? "" }, { enabled: Boolean(slug) });
  if (slug) {
    if (detail.isLoading) return <main className="container py-20">読み込み中…</main>;
    if (detail.isError) return <main className="container py-20"><h1 className="text-3xl font-bold">記事を取得できませんでした</h1><button type="button" onClick={() => detail.refetch()} className="mt-6 font-bold text-sky-700 underline">再読み込みする</button><Link href="/blog" className="ml-5 inline-block text-slate-600">ブログ一覧へ戻る</Link></main>;
    if (!detail.data) return <main className="container py-20"><h1 className="text-3xl font-bold">記事が見つかりません</h1><Link href="/blog" className="mt-6 inline-block text-sky-700">ブログ一覧へ戻る</Link></main>;
    const post = detail.data;
    return <main className="container max-w-4xl py-16"><Link href="/blog" className="text-sm font-bold text-sky-700">← BLOG</Link><p className="mt-10 font-mono text-xs tracking-widest text-sky-700">EMULABO INSIGHT</p><h1 className="mt-4 text-4xl font-bold leading-tight text-slate-950 md:text-6xl">{post.title}</h1><p className="mt-5 text-sm text-slate-500">{post.author} · {post.publishedAt ? new Date(post.publishedAt).toLocaleDateString("ja-JP") : ""}</p>{post.coverImageUrl && <img src={post.coverImageUrl} alt={post.coverImageAlt} className="mt-10 aspect-[16/8] w-full rounded-2xl object-cover" />}<p className="mt-10 text-lg font-semibold leading-8 text-slate-700">{post.excerpt}</p><article className="mt-8 whitespace-pre-wrap text-base leading-8 text-slate-700">{post.body}</article><CtaLink href="https://emulabo.com/contact" tracking={{ audience: "general", action: "content", placement: "blog_detail" }} className="mt-12 inline-flex rounded-md bg-sky-600 px-5 py-3 font-bold text-white">無料相談につなげる</CtaLink></main>;
  }
  return <main className="container py-16"><p className="font-mono text-xs tracking-widest text-sky-700">EMULABO INSIGHT</p><h1 className="mt-3 text-4xl font-bold text-slate-950">ブログ</h1><p className="mt-4 max-w-2xl leading-7 text-slate-600">教育設計、現場運用、AI活用を実務の視点から整理します。</p><div className="mt-10 grid gap-6 md:grid-cols-2">{list.isLoading ? <p className="rounded-xl bg-slate-100 p-6 text-sm text-slate-600">記事を読み込んでいます…</p> : list.isError ? <div className="rounded-xl border border-rose-200 bg-rose-50 p-6 text-sm text-rose-800"><p>記事を取得できませんでした。</p><button type="button" onClick={() => list.refetch()} className="mt-3 font-bold underline">再読み込みする</button></div> : list.data?.length === 0 ? <div className="rounded-xl border border-slate-200 bg-slate-50 p-6 text-sm text-slate-600 md:col-span-2"><p>公開中の記事はまだありません。</p><CtaLink href="https://emulabo.com/contact" tracking={{ audience: "general", action: "content", placement: "blog_empty" }} className="mt-3 inline-block font-bold text-sky-700">相談から最新情報を受け取る</CtaLink></div> : list.data?.map(post => <Link key={post.id} href={`/blog/${post.slug}`} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white"><>{post.coverImageUrl && <img src={post.coverImageUrl} alt={post.coverImageAlt} className="aspect-[16/9] w-full object-cover transition duration-300 group-hover:scale-[1.02]" />}<div className="p-6"><p className="text-xs text-slate-500">{post.publishedAt ? new Date(post.publishedAt).toLocaleDateString("ja-JP") : ""}</p><h2 className="mt-2 text-xl font-bold text-slate-950">{post.title}</h2><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">{post.excerpt}</p></div></></Link>)}</div></main>;
}
