/**
 * Design reminder — Operational Intelligence:
 * A precise editorial B2B experience: off-white space, deep navy structure,
 * controlled signal blue, asymmetric information rhythm, and one clear consultation CTA.
 */
import { useEffect, useState } from "react";
import { ArrowDownRight, ArrowRight, Menu, MoveUpRight, Plus, X } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { DEFAULT_SITE_CONTENT } from "@shared/cms";

const problemItems = ["店長によって、新人の育ち方が違う。", "研修を実施しても、現場の行動が変わらない。", "評価基準が曖昧で、何を教えるべきか分からない。", "優秀なスタッフのノウハウが、個人の中に留まっている。", "AIを導入したが、現場ではほとんど使われていない。", "店舗が増えるほど、教育品質を管理できなくなる。"];
const transformations = [["教育担当者しか教えられない", "誰が教えても一定品質"], ["研修して終わり", "現場行動まで評価できる"], ["スタッフごとにやり方が違う", "組織の共通基準がある"], ["AIを試しているだけ", "AIが日常業務に組み込まれている"], ["ノウハウが個人に蓄積", "組織の知識として蓄積"]];
const processSteps = [["01", "無料相談", "現状・課題・目標を整理。"], ["02", "課題整理", "人・教育・業務・AIの観点から構造化。"], ["03", "設計", "研修・制度・業務フローを設計。"], ["04", "実装", "実際の現場へ導入。"], ["05", "検証・改善", "運用結果から改善。"], ["06", "標準化", "組織内で継続できる状態へ。 "]];

function Multiline({ value }: { value: string }) {
  return <>{value.split("\n").map((line, index) => <span key={`${line}-${index}`}>{line}{index < value.split("\n").length - 1 && <br />}</span>)}</>;
}
function SectionLabel({ children, dark = false }: { children: string; dark?: boolean }) { return <p className={`section-label ${dark ? "section-label--dark" : ""}`}>{children}</p>; }
function PrimaryCta({ href, className = "" }: { href: string; className?: string }) { return <a className={`button button--primary ${className}`} href={href}>無料オンライン相談を予約する <ArrowRight size={17} aria-hidden="true" /></a>; }

export default function Home() {
  const [scrolled, setScrolled] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const { data: savedContent } = trpc.siteContent.public.useQuery(undefined, { staleTime: 60_000 });
  const { data: cmsNavigation = [] } = trpc.sitePages.publicNavigation.useQuery(undefined, { staleTime: 60_000 });
  const { data: cmsLinks = [] } = trpc.sitePages.publicLinks.useQuery(undefined, { staleTime: 60_000 });
  const content = savedContent ?? DEFAULT_SITE_CONTENT;
  const headerLinks = cmsLinks.filter(link => link.location === "header");
  const footerLinks = cmsLinks.filter(link => link.location === "footer");

  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 28); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []);
  const closeMenu = () => setMenuOpen(false);

  return <div className="site-shell">
    <a className="skip-link" href="#main-content">本文へ移動</a>
    <header className={`site-header ${scrolled ? "site-header--scrolled" : ""}`}>
      <div className="header-inner"><a className="brand" href="#top" aria-label="EMULABO トップへ"><img src="/manus-storage/emulabo-logo-symbol_160fa766.png" alt="" className="brand-symbol" /><span className="brand-lockup">EMULABO<i aria-hidden="true" /></span></a><nav className="desktop-nav" aria-label="主要ナビゲーション"><a href={content.audiences.corporate.href}>法人向け</a><a href={content.audiences.personal.href}>個人向け</a><a href="#approach">考え方</a><a href="#services">支援内容</a><a href="#profile">プロフィール</a><a href="/blog">ブログ</a><a href="/videos">動画</a>{cmsNavigation.map(page => <a href={`/${page.slug}`} key={page.slug}>{page.label}</a>)}{headerLinks.map(link => <a href={link.url} key={link.id} target={link.isExternal ? "_blank" : undefined} rel={link.isExternal ? "noreferrer" : undefined}>{link.label}</a>)}</nav><div className="header-cta"><a href={content.contactUrl} className="header-cta-link">無料相談を予約 <ArrowRight size={14} aria-hidden="true" /></a></div><button type="button" className="mobile-menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? "メニューを閉じる" : "メニューを開く"} aria-expanded={menuOpen}>{menuOpen ? <X size={22} /> : <Menu size={22} />}</button></div>
      <div className={`mobile-menu ${menuOpen ? "mobile-menu--open" : ""}`}><a href={content.audiences.corporate.href} onClick={closeMenu}>法人向け</a><a href={content.audiences.personal.href} onClick={closeMenu}>個人向け</a><a href="#approach" onClick={closeMenu}>考え方</a><a href="#services" onClick={closeMenu}>支援内容</a><a href="#profile" onClick={closeMenu}>プロフィール</a><a href="/blog" onClick={closeMenu}>ブログ</a><a href="/videos" onClick={closeMenu}>動画</a>{cmsNavigation.map(page => <a href={`/${page.slug}`} key={page.slug} onClick={closeMenu}>{page.label}</a>)}{headerLinks.map(link => <a href={link.url} key={link.id} target={link.isExternal ? "_blank" : undefined} rel={link.isExternal ? "noreferrer" : undefined} onClick={closeMenu}>{link.label}</a>)}<a href={content.contactUrl} className="button button--primary" onClick={closeMenu}>無料相談を予約する <ArrowRight size={17} /></a></div>
    </header>
    <main id="main-content">
      <section className="hero" id="top" aria-labelledby="hero-title"><div className="hero-image" aria-hidden="true" style={{ backgroundImage: `url("${content.assets.heroImageUrl}")` }} /><div className="hero-overlay" aria-hidden="true" /><div className="hero-grain" aria-hidden="true" /><div className="layout hero-layout"><div className="hero-copy" style={{ textAlign: content.hero.align }}><p className="hero-eyebrow">{content.hero.eyebrow}</p><h1 id="hero-title"><Multiline value={content.hero.title} /></h1><p className="hero-description">{content.hero.description}<strong>{content.hero.emphasis}</strong><br />フィットネス事業の「人が育つ仕組み」をつくります。</p><div className="hero-actions" style={{ justifyContent: content.hero.align === "center" ? "center" : content.hero.align === "right" ? "flex-end" : "flex-start" }}><PrimaryCta href={content.contactUrl} /><a href="#services" className="button button--text">支援内容を見る <ArrowDownRight size={18} aria-hidden="true" /></a></div><p className="hero-note">{content.hero.note}</p></div><aside className="hero-system" aria-label="支援領域"><div className="hero-brand-sigil"><img src="/manus-storage/emulabo-logo-symbol_160fa766.png" alt="" /><span>EMULABO<br />OPERATIONAL INTELLIGENCE</span></div><div className="hero-system-top"><span>EMULABO METHOD</span><span>01—06</span></div><p>知るだけで終わらせない。<br /><strong>現場で、続く状態まで。</strong></p><div className="hero-system-line" /><div className="hero-system-bottom"><span>EDUCATION</span><span>OPERATIONS</span><span>AI</span></div></aside></div></section>
      <section className="signal-strip" aria-label="EMULABOの実務経験"><div className="layout signal-grid">{content.signals.map(signal => <div className="signal-item" key={`${signal.number}-${signal.label}`}><strong>{signal.number}<small>{signal.unit}</small></strong><span>{signal.label}</span></div>)}</div></section>
      <section className="audience-section" aria-labelledby="audience-title"><div className="layout audience-heading"><SectionLabel>START HERE</SectionLabel><div><h2 id="audience-title">あなたの課題に、<br /><em>近い入口から。</em></h2><p>法人の仕組みづくりも、個人の継続も、まずは現在地を一緒に整理します。</p></div></div><div className="layout audience-grid"><a className="audience-card audience-card--corporate" href={content.audiences.corporate.href}><img src={content.assets.workshopImageUrl} alt="法人向け研修でチームが学んでいる様子" /><div><span>{content.audiences.corporate.eyebrow}</span><h3>{content.audiences.corporate.title}</h3><p>{content.audiences.corporate.text}</p><b>{content.audiences.corporate.ctaLabel} <ArrowRight size={16} aria-hidden="true" /></b></div></a><a className="audience-card audience-card--personal" href={content.audiences.personal.href}><img src={content.assets.consultationImageUrl} alt="個人の課題を相談している様子" /><div><span>{content.audiences.personal.eyebrow}</span><h3>{content.audiences.personal.title}</h3><p>{content.audiences.personal.text}</p><b>{content.audiences.personal.ctaLabel} <ArrowRight size={16} aria-hidden="true" /></b></div></a></div></section>
      <section className="principle-band" aria-labelledby="principle-title"><div className="layout principle-layout"><SectionLabel>EMULABO PHILOSOPHY</SectionLabel><div className="principle-copy"><h2 id="principle-title">「知って終わり」をなくし、<br /><em>目標達成まで伴走する。</em></h2><p>専門知識をわかる言葉へ翻訳し、明日から実行できる手順へ落とし込む。理解・実践・定着まで、教育と現場を一つの流れとして支援します。</p></div><div className="principle-steps"><span><b>01</b>翻訳する</span><span><b>02</b>実践する</span><span><b>03</b>定着させる</span></div></div></section>
      <section className="section visual-proof-section" aria-labelledby="visual-proof-title"><div className="layout split-heading"><SectionLabel>EMULABO IN PRACTICE</SectionLabel><div><h2 id="visual-proof-title">伴走の価値を、<br /><em>現場の景色で伝える。</em></h2><p className="section-intro">相談、研修、運用。支援の各フェーズを、実際の人と場のイメージで共有します。</p></div></div><div className="layout visual-proof-grid"><article className="visual-proof-card visual-proof-card--lead"><img src={content.assets.consultationImageUrl} alt="相談者とコンサルタントが教育ロードマップを確認している様子" /><div className="visual-proof-overlay"><span>01 — CONSULTATION</span><h3>課題を一緒に、<br />言葉にする。</h3><a href={content.contactUrl}>無料相談から始める <ArrowRight size={15} /></a></div></article><article className="visual-proof-card"><img src={content.assets.workshopImageUrl} alt="トレーナー向け研修を実施している様子" /><div className="visual-proof-caption"><span>02 — WORKSHOP</span><h3>知識を、現場で<br />使える形へ。</h3></div></article><article className="visual-proof-card"><img src={content.assets.operationsImageUrl} alt="チームが運用改善の次のアクションを確認している様子" /><div className="visual-proof-caption"><span>03 — OPERATIONS</span><h3>続く仕組みを、<br />チームに残す。</h3></div></article></div></section>
      <section className="section problem-section" id="problems" aria-labelledby="problems-title"><div className="layout split-heading"><SectionLabel>01 — PROBLEM</SectionLabel><div><h2 id="problems-title">こんな状態に、<br />なっていませんか？</h2><p className="section-intro">教育・運用・AI活用の課題は、日々の小さな違和感として現れます。<br className="desktop-only" />その違和感を、組織が前へ進むための論点に変えます。</p></div></div><div className="layout problem-layout"><div className="problem-rail" aria-hidden="true"><span>DIAGNOSE</span></div><div className="problem-grid">{problemItems.map((problem, index) => <article className="problem-card" key={problem}><span>0{index + 1}</span><h3>{problem}</h3><ArrowDownRight size={22} aria-hidden="true" /></article>)}</div></div><div className="layout problem-conclusion"><span>01</span><p>問題は、人ではなく<strong>「仕組み」</strong>かもしれません。</p><a href={content.contactUrl}>課題を整理する <ArrowRight size={16} /></a></div></section>
      <section className="section why-section" id="approach" aria-labelledby="why-title"><div className="layout why-layout"><SectionLabel>02 — WHY</SectionLabel><div className="why-main"><h2 id="why-title">研修資料を渡すだけでは、<br /><em>現場は変わりません。</em></h2><div className="why-body"><p>知識を伝えるだけでは、「知っている」状態までしかつくれません。必要なのは、知識が行動になり、評価され、現場に残り続けることです。</p><div className="learning-chain" aria-label="学びが定着するプロセス">{["知る", "できる", "評価される", "継続される"].map((item, index) => <div className="chain-item" key={item}><b>0{index + 1}</b><span>{item}</span></div>)}</div><p className="why-emphasis">EMULABOは、<strong>教育 × 評価 × 現場運用 × AI</strong> を分断せず、一つの仕組みとして設計します。</p></div></div></div></section>
      <section className="section solution-section" aria-labelledby="solution-title"><div className="layout solution-heading"><SectionLabel dark>03 — SOLUTION</SectionLabel><div><h2 id="solution-title">教育を「イベント」から、<br />「仕組み」へ。</h2><p>相談の先にあるのは、単発の研修ではありません。<br />組織が学び、実践し、改善を続ける循環です。</p></div></div><div className="layout solution-visual-wrap"><div className="solution-visual"><svg className="solution-orbit" viewBox="0 0 700 560" aria-hidden="true"><path d="M141 310 C141 134 305 76 448 116 C609 161 635 364 486 447 C332 533 129 478 113 326" fill="none" /><path d="M113 326 l3 -30 l24 16" fill="none" /><circle cx="141" cy="310" r="5" /><circle cx="291" cy="116" r="5" /><circle cx="526" cy="190" r="5" /><circle cx="510" cy="406" r="5" /><circle cx="276" cy="464" r="5" /></svg><div className="orbit-center"><span>EMULABO</span><strong>現場で<br />動く仕組み</strong></div>{[["01", "現状分析", "orbit-node--one"], ["02", "教育設計", "orbit-node--two"], ["03", "研修・実践", "orbit-node--three"], ["04", "評価・改善", "orbit-node--four"], ["05", "標準化", "orbit-node--five"], ["06", "AI・DX", "orbit-node--six"]].map(([number, title, className]) => <div className={`orbit-node ${className}`} key={number}><b>{number}</b><span>{title}</span></div>)}</div><p className="solution-caption"><span>THE OPERATING LOOP</span> 一度つくって終わらせず、運用の中で学びと改善が積み上がる状態を目指します。</p></div></section>
      <section className="section services-section" id="services" aria-labelledby="services-title"><div className="layout split-heading service-heading"><SectionLabel>04 — SERVICE</SectionLabel><div><h2 id="services-title">教育と現場をつなぐ、<br />3つの支援。</h2><p className="section-intro">課題の一部だけを切り取らず、必要な領域を組み合わせて支援します。</p></div></div><div className="layout services-list">{content.services.map(service => <article className="service-row" key={service.number}><div className="service-num">{service.number}</div><div className="service-title"><h3>{service.title}</h3><p>{service.lead}</p></div><div className="service-detail"><p>{service.text}</p><ul>{service.examples.map(example => <li key={example}>{example}</li>)}</ul></div></article>)}</div><div className="layout restrained-cta"><div><p>どの領域から着手すべきか、まだ決まっていなくても構いません。</p>{content.resources.corporate.url && <a className="resource-link" href={content.resources.corporate.url} target={content.resources.corporate.url.startsWith("http") ? "_blank" : undefined} rel={content.resources.corporate.url.startsWith("http") ? "noreferrer" : undefined}>{content.resources.corporate.label} <MoveUpRight size={16} aria-hidden="true" /></a>}</div><PrimaryCta href={content.contactUrl} /></div></section>
      <section className="section change-section" aria-labelledby="change-title"><div className="layout split-heading"><SectionLabel>05 — BEFORE / AFTER</SectionLabel><div><h2 id="change-title">EMULABOが目指す変化</h2><p className="section-intro">教育を「実施すること」から、組織の力として「残ること」へ。</p></div></div><div className="layout transformation-list">{transformations.map(([before, after], index) => <article className="transformation" key={before}><span className="transformation-no">0{index + 1}</span><p className="before"><small>BEFORE</small>{before}</p><ArrowRight className="transformation-arrow" size={23} aria-hidden="true" /><p className="after"><small>AFTER</small>{after}</p></article>)}</div></section>
      <section className="section cases-section" id="cases" aria-labelledby="cases-title"><div className="layout split-heading"><SectionLabel dark>06 — CASES</SectionLabel><div><h2 id="cases-title">数字の先にある、<br />「できる状態」をつくる。</h2><p className="section-intro">何を導入したかではなく、現場にどんな共通基準が生まれたかを大切にします。</p></div></div><div className="layout case-grid"><article className="case-card case-card--main"><div className="case-card-top"><span>CASE 01</span><span>EDUCATION SYSTEM</span></div><h3><Multiline value={content.caseStudy.title} /></h3><dl><div><dt>課題</dt><dd>{content.caseStudy.challenge}</dd></div><div><dt>実施</dt><dd>{content.caseStudy.action}</dd></div><div><dt>変化</dt><dd>{content.caseStudy.outcome}</dd></div></dl><div className="case-card-foot"><span>担当領域</span><p>{content.caseStudy.scope}</p></div><a className="case-detail-link" href={content.contactUrl}>公開可能な範囲で事例を確認する <ArrowRight size={15} aria-hidden="true" /></a></article><div className="case-art" role="img" aria-label="教育の仕組みを象徴する構造的なオブジェクト" style={{ backgroundImage: `url("${content.assets.caseImageUrl}")` }} /></div><div className="layout case-cta"><p>自社の場合、どこから整えるべきか。<br />まずは現状を伺い、論点を整理します。</p><PrimaryCta href={content.contactUrl} /></div></section>
      <section className="section process-section" aria-labelledby="process-title"><div className="layout split-heading"><SectionLabel>07 — PROCESS</SectionLabel><div><h2 id="process-title">相談から実装まで</h2><p className="section-intro">「コンサルを受けたら何が起こるか分からない」という不安をなくし、進め方を最初に共有します。</p></div></div><div className="layout process-rail">{processSteps.map(([number, title, text], index) => <article className="process-step" key={number}><div className="process-line"><span>{number}</span>{index < processSteps.length - 1 && <i />}</div><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
      <section className="products-section" aria-labelledby="products-title"><div className="layout products-heading"><SectionLabel dark>08 — PRODUCTS</SectionLabel><div><h2 id="products-title">AIを語るだけではなく、<br />自分たちでもつくる。</h2><p>EMULABOでは、AI活用を提案するだけでなく、教育・業務領域のAIプロダクトを開発しています。その知見を法人支援にも還元します。</p></div></div><div className="layout products-grid"><a className="product-card product-card--task" href="https://emulabo-trainer-business-os.netlify.app" target="_blank" rel="noreferrer"><span>AI WORKSPACE</span><h3>TaskAI<br /><i>Business OS</i></h3><p>日々の業務を「終わらせる」ための、AI業務ワークスペース。</p><small className="product-context">業務設計・成果物・実行速度を、現場で接続する。</small><b>プロダクトを見る <MoveUpRight size={17} /></b></a><a className="product-card product-card--dictionary" href="https://emulabo-dictionary.netlify.app" target="_blank" rel="noreferrer"><span>KNOWLEDGE BASE</span><h3>EMULABO<br /><i>Trainer's Dictionary</i></h3><p>専門知識を、現場で使える言葉へ翻訳する知識の基盤。</p><small className="product-context">教育基準と実践知を、組織に残すための実装。</small><b>辞書を見る <MoveUpRight size={17} /></b></a></div></section>
      <section className="section profile-section" id="profile" aria-labelledby="profile-title"><div className="layout profile-grid"><div className="profile-image-wrap"><img src={content.assets.profileImageUrl} alt="教育運用の資料を整理する様子" /><span>FIELD<br />KNOWLEDGE<br />/ 15 YEARS</span></div><div className="profile-copy"><SectionLabel>09 — PROFILE</SectionLabel><h2 id="profile-title"><Multiline value={content.profile.heading} /></h2><p className="profile-name">{content.profile.name}</p><blockquote><Multiline value={content.profile.quote} /></blockquote><p>{content.profile.bio}</p><div className="credentials">{content.profile.credentials.map(credential => <span key={credential}>{credential}</span>)}</div><a href={content.contactUrl} className="profile-link">無料相談を予約する <ArrowRight size={17} /></a><a href={content.contactUrl} className="profile-support-link">支援範囲・進め方を相談で確認する <ArrowRight size={14} aria-hidden="true" /></a></div></div></section>
      <section className="section faq-section" aria-labelledby="faq-title"><div className="layout split-heading"><SectionLabel>10 — FAQ</SectionLabel><div><h2 id="faq-title">よくあるご質問</h2><p className="section-intro">相談の前に、ご不安な点をご確認ください。</p></div></div><div className="layout faq-list">{content.faqs.map((faq, index) => <article className={`faq-item ${openFaq === index ? "faq-item--open" : ""}`} key={faq.question}><button type="button" onClick={() => setOpenFaq(openFaq === index ? null : index)} aria-expanded={openFaq === index}><span>Q{String(index + 1).padStart(2, "0")}</span><strong>{faq.question}</strong><Plus size={20} aria-hidden="true" /></button><div className="faq-answer"><p>{faq.answer}</p></div></article>)}</div><div className="layout faq-cta"><p>掲載内容だけでは判断しにくい場合も、現状を伺い、確認可能な範囲からご案内します。</p><a href={content.contactUrl}>相談前の疑問を話す <ArrowRight size={16} aria-hidden="true" /></a></div></section>
      <section className="section knowledge-section" aria-labelledby="knowledge-title"><div className="layout split-heading"><SectionLabel>11 — KNOWLEDGE</SectionLabel><div><h2 id="knowledge-title">学びを、<br /><em>次の相談へつなぐ。</em></h2><p className="section-intro">ブログと動画で、教育設計・現場運用・AI活用の考え方を共有します。公開コンテンツがない場合も、相談から現在地を整理できます。</p></div></div><div className="layout knowledge-grid"><a className="knowledge-card" href="/blog"><img src={content.assets.workshopImageUrl} alt="研修で知識を実践へ変えている様子" /><div><span>BLOG / INSIGHT</span><h3>現場で使える知識を読む</h3><p>教育・評価・運用を、明日から使える論点として整理します。</p><b>ブログを見る <ArrowRight size={16} aria-hidden="true" /></b></div></a><a className="knowledge-card" href="/videos"><img src={content.assets.operationsImageUrl} alt="チームが運用改善を確認している様子" /><div><span>VIDEO / FIELD NOTE</span><h3>支援の現場を動画で見る</h3><p>研修や運用の考え方を、場面と手順から確認できます。</p><b>動画を見る <ArrowRight size={16} aria-hidden="true" /></b></div></a></div></section>
      <section className="final-cta" aria-labelledby="final-cta-title"><div className="final-cta-art" aria-hidden="true" /><div className="layout final-cta-inner"><div style={{ textAlign: content.finalCta.align }}><SectionLabel dark>START WITH A CONVERSATION</SectionLabel><h2 id="final-cta-title"><Multiline value={content.finalCta.title} /></h2><p>{content.finalCta.text}</p><PrimaryCta href={content.contactUrl} /><span className="final-note">{content.finalCta.note}</span></div><div className="final-cta-index"><span>EMULABO</span><b>01<br />02<br />03<br />04</b><small>EDUCATION<br />OPERATIONS<br />AI</small></div></div></section>
    </main>
    <footer className="site-footer"><div className="layout footer-inner"><a className="brand brand--footer" href="#top"><img src="/manus-storage/emulabo-logo-symbol_160fa766.png" alt="" className="brand-symbol" /><span className="brand-lockup">EMULABO<i aria-hidden="true" /></span></a><div>{footerLinks.map(link => <a href={link.url} key={link.id} target={link.isExternal ? "_blank" : undefined} rel={link.isExternal ? "noreferrer" : undefined}>{link.label}</a>)}<a href="https://emulabo.com/">emulabo.com</a><span>© 2026 EMULABO</span></div></div></footer>
    <a className="mobile-consultation" href={content.contactUrl}>無料相談を予約する <ArrowRight size={16} /></a>
  </div>;
}
